### ISSUE TITLE
CloudFlare worker

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne-graphql-proxy#29]
We could have an `contrib.cloudflare` module/package exporting a function for easy AGP worker creation for cloudflare, eg:

```python
from ariadne_graphql_proxy.contrib.cloudflare import create_cf_worker


worker = create_cf_worker(...)
```

**Comment by mat-sop** [comment]
Cloudflare workers don't properly support python, they require js/ts. The solution mentioned [here](https://developers.cloudflare.com/workers/learning/languages/) compiles python to js, but it lacks most of the standard library and focuses on js libraries. So for now I'm closing this issue.

**Comment by rafalp** [comment]
Yup. We should focus on alternatives that are Python-native, and only then move on to more complex alternatives like transpiling (which sound like something that has no right to work for project of our complexity).
